/**
 * NSE Stock Universe — 250 stocks
 * Nifty 500 representatives, F&O names, Midcap, Smallcap, Liquid stocks
 * Each entry: { sym, name, sector, industry, cap, foStock }
 */

const STOCK_UNIVERSE = [
  // ── Nifty 50 / Large Cap ──────────────────────────────────────────────────
  {sym:'RELIANCE.NS',   name:'Reliance Industries',    sector:'Energy',        industry:'Oil & Gas',          cap:'Large', foStock:true},
  {sym:'TCS.NS',        name:'TCS',                    sector:'IT',            industry:'IT Services',        cap:'Large', foStock:true},
  {sym:'HDFCBANK.NS',   name:'HDFC Bank',              sector:'Banking',       industry:'Private Bank',       cap:'Large', foStock:true},
  {sym:'INFY.NS',       name:'Infosys',                sector:'IT',            industry:'IT Services',        cap:'Large', foStock:true},
  {sym:'ICICIBANK.NS',  name:'ICICI Bank',             sector:'Banking',       industry:'Private Bank',       cap:'Large', foStock:true},
  {sym:'HINDUNILVR.NS', name:'HUL',                    sector:'FMCG',          industry:'Personal Products',  cap:'Large', foStock:true},
  {sym:'ITC.NS',        name:'ITC',                    sector:'FMCG',          industry:'Tobacco & FMCG',     cap:'Large', foStock:true},
  {sym:'SBIN.NS',       name:'SBI',                    sector:'Banking',       industry:'Public Bank',        cap:'Large', foStock:true},
  {sym:'BHARTIARTL.NS', name:'Bharti Airtel',          sector:'Telecom',       industry:'Telecom Services',   cap:'Large', foStock:true},
  {sym:'BAJFINANCE.NS', name:'Bajaj Finance',          sector:'NBFC',          industry:'Consumer Finance',   cap:'Large', foStock:true},
  {sym:'KOTAKBANK.NS',  name:'Kotak Mahindra Bank',    sector:'Banking',       industry:'Private Bank',       cap:'Large', foStock:true},
  {sym:'LT.NS',         name:'Larsen & Toubro',        sector:'Infra',         industry:'Engineering',        cap:'Large', foStock:true},
  {sym:'HCLTECH.NS',    name:'HCL Technologies',       sector:'IT',            industry:'IT Services',        cap:'Large', foStock:true},
  {sym:'WIPRO.NS',      name:'Wipro',                  sector:'IT',            industry:'IT Services',        cap:'Large', foStock:true},
  {sym:'ASIANPAINT.NS', name:'Asian Paints',           sector:'Consumer',      industry:'Paints',             cap:'Large', foStock:true},
  {sym:'AXISBANK.NS',   name:'Axis Bank',              sector:'Banking',       industry:'Private Bank',       cap:'Large', foStock:true},
  {sym:'MARUTI.NS',     name:'Maruti Suzuki',          sector:'Auto',          industry:'Passenger Vehicles', cap:'Large', foStock:true},
  {sym:'SUNPHARMA.NS',  name:'Sun Pharma',             sector:'Pharma',        industry:'Pharma',             cap:'Large', foStock:true},
  {sym:'TITAN.NS',      name:'Titan Company',          sector:'Consumer',      industry:'Jewellery',          cap:'Large', foStock:true},
  {sym:'NTPC.NS',       name:'NTPC',                   sector:'Power',         industry:'Power Generation',   cap:'Large', foStock:true},
  {sym:'ONGC.NS',       name:'ONGC',                   sector:'Energy',        industry:'Oil & Gas',          cap:'Large', foStock:true},
  {sym:'TATASTEEL.NS',  name:'Tata Steel',             sector:'Metals',        industry:'Steel',              cap:'Large', foStock:true},
  {sym:'BAJAJFINSV.NS', name:'Bajaj Finserv',          sector:'NBFC',          industry:'Diversified Finance',cap:'Large', foStock:true},
  {sym:'JSWSTEEL.NS',   name:'JSW Steel',              sector:'Metals',        industry:'Steel',              cap:'Large', foStock:true},
  {sym:'TECHM.NS',      name:'Tech Mahindra',          sector:'IT',            industry:'IT Services',        cap:'Large', foStock:true},
  {sym:'HEROMOTOCO.NS', name:'Hero MotoCorp',          sector:'Auto',          industry:'2-Wheelers',         cap:'Large', foStock:true},
  {sym:'DRREDDY.NS',    name:'Dr Reddys',              sector:'Pharma',        industry:'Pharma',             cap:'Large', foStock:true},
  {sym:'DIVISLAB.NS',   name:'Divis Labs',             sector:'Pharma',        industry:'API',                cap:'Large', foStock:true},
  {sym:'BAJAJ-AUTO.NS', name:'Bajaj Auto',             sector:'Auto',          industry:'2-Wheelers',         cap:'Large', foStock:true},
  {sym:'CIPLA.NS',      name:'Cipla',                  sector:'Pharma',        industry:'Pharma',             cap:'Large', foStock:true},
  {sym:'ULTRACEMCO.NS', name:'UltraTech Cement',       sector:'Cement',        industry:'Cement',             cap:'Large', foStock:true},
  {sym:'POWERGRID.NS',  name:'Power Grid Corp',        sector:'Power',         industry:'Power Transmission', cap:'Large', foStock:true},
  {sym:'NESTLEIND.NS',  name:'Nestle India',           sector:'FMCG',          industry:'Food Products',      cap:'Large', foStock:false},
  {sym:'GRASIM.NS',     name:'Grasim Industries',      sector:'Conglomerate',  industry:'Diversified',        cap:'Large', foStock:true},
  {sym:'HAL.NS',        name:'HAL',                    sector:'Defence',       industry:'Aerospace & Defence',cap:'Large', foStock:true},
  {sym:'HAVELLS.NS',    name:'Havells India',          sector:'Electrical',    industry:'Electrical Equip',   cap:'Large', foStock:true},
  {sym:'HINDALCO.NS',   name:'Hindalco Industries',    sector:'Metals',        industry:'Aluminium',          cap:'Large', foStock:true},
  {sym:'INDIGO.NS',     name:'IndiGo',                 sector:'Aviation',      industry:'Airlines',           cap:'Large', foStock:true},
  {sym:'IRFC.NS',       name:'IRFC',                   sector:'NBFC',          industry:'Govt Finance',       cap:'Large', foStock:true},
  {sym:'M&M.NS',        name:'Mahindra & Mahindra',    sector:'Auto',          industry:'Utility Vehicles',   cap:'Large', foStock:true},
  {sym:'BPCL.NS',       name:'BPCL',                   sector:'Energy',        industry:'Oil Refining',       cap:'Large', foStock:true},
  {sym:'DABUR.NS',      name:'Dabur India',            sector:'FMCG',          industry:'Personal Products',  cap:'Large', foStock:true},
  {sym:'DLF.NS',        name:'DLF',                    sector:'Realty',        industry:'Real Estate',        cap:'Large', foStock:true},
  {sym:'GAIL.NS',       name:'GAIL',                   sector:'Energy',        industry:'Gas Distribution',   cap:'Large', foStock:true},
  {sym:'PFC.NS',        name:'Power Finance Corp',     sector:'NBFC',          industry:'Govt Finance',       cap:'Large', foStock:true},
  {sym:'SHREECEM.NS',   name:'Shree Cement',           sector:'Cement',        industry:'Cement',             cap:'Large', foStock:true},
  {sym:'SIEMENS.NS',    name:'Siemens India',          sector:'Capital Goods', industry:'Industrial Equip',   cap:'Large', foStock:true},
  {sym:'TATAMOTORS.NS', name:'Tata Motors',            sector:'Auto',          industry:'Commercial Vehicles',cap:'Large', foStock:true},
  {sym:'TATACONSUM.NS', name:'Tata Consumer',          sector:'FMCG',          industry:'Food & Beverages',   cap:'Large', foStock:true},
  {sym:'UPL.NS',        name:'UPL',                    sector:'Agrochem',      industry:'Agrochemicals',      cap:'Large', foStock:true},
  {sym:'VEDL.NS',       name:'Vedanta',                sector:'Metals',        industry:'Diversified Metals', cap:'Large', foStock:true},
  {sym:'ZOMATO.NS',     name:'Zomato',                 sector:'Internet',      industry:'Food Tech',          cap:'Large', foStock:true},
  {sym:'ZYDUSLIFE.NS',  name:'Zydus Lifesciences',     sector:'Pharma',        industry:'Pharma',             cap:'Large', foStock:true},
  {sym:'ADANIENT.NS',   name:'Adani Enterprises',      sector:'Conglomerate',  industry:'Diversified',        cap:'Large', foStock:true},
  {sym:'ADANIPORTS.NS', name:'Adani Ports',            sector:'Logistics',     industry:'Ports',              cap:'Large', foStock:true},
  // ── Nifty Midcap ─────────────────────────────────────────────────────────
  {sym:'DIXON.NS',      name:'Dixon Technologies',     sector:'Electronics',   industry:'Contract Mfg',       cap:'Mid', foStock:true},
  {sym:'POLYCAB.NS',    name:'Polycab India',          sector:'Cables',        industry:'Cables & Wires',     cap:'Mid', foStock:true},
  {sym:'TATAELXSI.NS',  name:'Tata Elxsi',             sector:'IT',            industry:'Design Services',    cap:'Mid', foStock:true},
  {sym:'PERSISTENT.NS', name:'Persistent Systems',     sector:'IT',            industry:'IT Services',        cap:'Mid', foStock:true},
  {sym:'COFORGE.NS',    name:'Coforge',                sector:'IT',            industry:'IT Services',        cap:'Mid', foStock:true},
  {sym:'APOLLOHOSP.NS', name:'Apollo Hospitals',       sector:'Healthcare',    industry:'Hospitals',          cap:'Mid', foStock:true},
  {sym:'ASTRAL.NS',     name:'Astral',                 sector:'Pipes',         industry:'Plastic Pipes',      cap:'Mid', foStock:true},
  {sym:'AUROPHARMA.NS', name:'Aurobindo Pharma',       sector:'Pharma',        industry:'Generics',           cap:'Mid', foStock:true},
  {sym:'CAMS.NS',       name:'CAMS',                   sector:'Fintech',       industry:'Financial Services', cap:'Mid', foStock:true},
  {sym:'GRINDWELL.NS',  name:'Grindwell Norton',       sector:'Industrials',   industry:'Abrasives',          cap:'Mid', foStock:false},
  {sym:'LTIM.NS',       name:'LTIMindtree',            sector:'IT',            industry:'IT Services',        cap:'Mid', foStock:true},
  {sym:'MPHASIS.NS',    name:'Mphasis',                sector:'IT',            industry:'IT Services',        cap:'Mid', foStock:true},
  {sym:'CGPOWER.NS',    name:'CG Power',               sector:'Electrical',    industry:'Electrical Equip',   cap:'Mid', foStock:true},
  {sym:'PIIND.NS',      name:'PI Industries',          sector:'Agrochem',      industry:'Agrochemicals',      cap:'Mid', foStock:true},
  {sym:'SRF.NS',        name:'SRF',                    sector:'Chemicals',     industry:'Specialty Chemicals',cap:'Mid', foStock:true},
  {sym:'CHOLAFIN.NS',   name:'Chola Finance',          sector:'NBFC',          industry:'Vehicle Finance',    cap:'Mid', foStock:true},
  {sym:'CUMMINSIND.NS', name:'Cummins India',          sector:'Industrials',   industry:'Engines',            cap:'Mid', foStock:true},
  {sym:'DEEPAKNTR.NS',  name:'Deepak Nitrite',         sector:'Chemicals',     industry:'Specialty Chemicals',cap:'Mid', foStock:true},
  {sym:'IRCTC.NS',      name:'IRCTC',                  sector:'Travel',        industry:'Tourism',            cap:'Mid', foStock:true},
  {sym:'LUPIN.NS',      name:'Lupin',                  sector:'Pharma',        industry:'Generics',           cap:'Mid', foStock:true},
  {sym:'MARICO.NS',     name:'Marico',                 sector:'FMCG',          industry:'Personal Products',  cap:'Mid', foStock:true},
  {sym:'MAXHEALTH.NS',  name:'Max Healthcare',         sector:'Healthcare',    industry:'Hospitals',          cap:'Mid', foStock:true},
  {sym:'MOTHERSON.NS',  name:'Motherson Sumi',         sector:'Auto Ancillary',industry:'Auto Parts',         cap:'Mid', foStock:true},
  {sym:'MUTHOOTFIN.NS', name:'Muthoot Finance',        sector:'NBFC',          industry:'Gold Finance',       cap:'Mid', foStock:true},
  {sym:'NAUKRI.NS',     name:'Info Edge',              sector:'Internet',      industry:'Job Portal',         cap:'Mid', foStock:true},
  {sym:'OBEROIRLTY.NS', name:'Oberoi Realty',          sector:'Realty',        industry:'Real Estate',        cap:'Mid', foStock:true},
  {sym:'PAGEIND.NS',    name:'Page Industries',        sector:'Consumer',      industry:'Innerwear',          cap:'Mid', foStock:true},
  {sym:'PHOENIXLTD.NS', name:'Phoenix Mills',          sector:'Realty',        industry:'Retail Malls',       cap:'Mid', foStock:true},
  {sym:'PRESTIGE.NS',   name:'Prestige Estates',       sector:'Realty',        industry:'Real Estate',        cap:'Mid', foStock:true},
  {sym:'KEI.NS',        name:'KEI Industries',         sector:'Cables',        industry:'Cables & Wires',     cap:'Mid', foStock:true},
  {sym:'KPITTECH.NS',   name:'KPIT Technologies',      sector:'IT',            industry:'Automotive Tech',    cap:'Mid', foStock:true},
  {sym:'APOLLOTYRE.NS', name:'Apollo Tyres',           sector:'Auto Ancillary',industry:'Tyres',              cap:'Mid', foStock:true},
  {sym:'ASHOKLEY.NS',   name:'Ashok Leyland',          sector:'Auto',          industry:'Commercial Vehicles',cap:'Mid', foStock:true},
  {sym:'BIOCON.NS',     name:'Biocon',                 sector:'Pharma',        industry:'Biologics',          cap:'Mid', foStock:true},
  {sym:'BHEL.NS',       name:'BHEL',                   sector:'Capital Goods', industry:'Heavy Engineering',  cap:'Mid', foStock:true},
  {sym:'CANBK.NS',      name:'Canara Bank',            sector:'Banking',       industry:'Public Bank',        cap:'Mid', foStock:true},
  {sym:'CONCOR.NS',     name:'Container Corp',         sector:'Logistics',     industry:'Rail Logistics',     cap:'Mid', foStock:true},
  {sym:'FEDERALBNK.NS', name:'Federal Bank',           sector:'Banking',       industry:'Private Bank',       cap:'Mid', foStock:true},
  {sym:'GODREJPROP.NS', name:'Godrej Properties',      sector:'Realty',        industry:'Real Estate',        cap:'Mid', foStock:true},
  {sym:'IDFCFIRSTB.NS', name:'IDFC First Bank',        sector:'Banking',       industry:'Private Bank',       cap:'Mid', foStock:true},
  {sym:'INDHOTEL.NS',   name:'Indian Hotels',          sector:'Hotels',        industry:'Hotels & Resorts',   cap:'Mid', foStock:true},
  {sym:'JUBLFOOD.NS',   name:'Jubilant FoodWorks',     sector:'QSR',           industry:'Restaurants',        cap:'Mid', foStock:true},
  {sym:'MANAPPURAM.NS', name:'Manappuram Finance',     sector:'NBFC',          industry:'Gold Finance',       cap:'Mid', foStock:true},
  {sym:'NYKAA.NS',      name:'Nykaa',                  sector:'Retail',        industry:'Beauty Retail',      cap:'Mid', foStock:true},
  {sym:'PNB.NS',        name:'Punjab National Bank',   sector:'Banking',       industry:'Public Bank',        cap:'Mid', foStock:true},
  {sym:'SAIL.NS',       name:'SAIL',                   sector:'Metals',        industry:'Steel',              cap:'Mid', foStock:true},
  {sym:'TATACOMM.NS',   name:'Tata Communications',    sector:'Telecom',       industry:'Data Services',      cap:'Mid', foStock:true},
  {sym:'TATAPOWER.NS',  name:'Tata Power',             sector:'Power',         industry:'Integrated Power',   cap:'Mid', foStock:true},
  {sym:'TORNTPHARM.NS', name:'Torrent Pharma',         sector:'Pharma',        industry:'Pharma',             cap:'Mid', foStock:true},
  {sym:'TRENT.NS',      name:'Trent',                  sector:'Retail',        industry:'Fashion Retail',     cap:'Mid', foStock:true},
  {sym:'ABCAPITAL.NS',  name:'Aditya Birla Capital',   sector:'NBFC',          industry:'Diversified Finance',cap:'Mid', foStock:true},
  {sym:'ALKEM.NS',      name:'Alkem Laboratories',     sector:'Pharma',        industry:'Pharma',             cap:'Mid', foStock:true},
  {sym:'BALKRISIND.NS', name:'Balkrishna Industries',  sector:'Auto Ancillary',industry:'Tyres',              cap:'Mid', foStock:true},
  {sym:'BRIGADE.NS',    name:'Brigade Enterprises',    sector:'Realty',        industry:'Real Estate',        cap:'Mid', foStock:false},
  {sym:'CROMPTON.NS',   name:'Crompton Greaves',       sector:'Electrical',    industry:'Consumer Electrical',cap:'Mid', foStock:true},
  {sym:'DALBHARAT.NS',  name:'Dalmia Bharat',          sector:'Cement',        industry:'Cement',             cap:'Mid', foStock:true},
  {sym:'ELGIEQUIP.NS',  name:'Elgi Equipments',        sector:'Industrials',   industry:'Compressors',        cap:'Mid', foStock:false},
  {sym:'GLAXO.NS',      name:'GSK Pharma',             sector:'Pharma',        industry:'Pharma',             cap:'Mid', foStock:false},
  {sym:'JKCEMENT.NS',   name:'JK Cement',              sector:'Cement',        industry:'Cement',             cap:'Mid', foStock:true},
  {sym:'KAJARIACER.NS', name:'Kajaria Ceramics',       sector:'Consumer',      industry:'Ceramics',           cap:'Mid', foStock:true},
  {sym:'LICHSGFIN.NS',  name:'LIC Housing Finance',    sector:'Housing Finance',industry:'Mortgage Finance',  cap:'Mid', foStock:true},
  {sym:'LINDEINDIA.NS', name:'Linde India',            sector:'Chemicals',     industry:'Industrial Gases',   cap:'Mid', foStock:false},
  {sym:'MCX.NS',        name:'MCX',                    sector:'Fintech',       industry:'Commodity Exchange', cap:'Mid', foStock:true},
  {sym:'METROPOLIS.NS', name:'Metropolis Healthcare',  sector:'Healthcare',    industry:'Diagnostics',        cap:'Mid', foStock:true},
  {sym:'NAVINFLUOR.NS', name:'Navin Fluorine',         sector:'Chemicals',     industry:'Fluorochemicals',    cap:'Mid', foStock:true},
  {sym:'OFSS.NS',       name:'Oracle Financial',       sector:'IT',            industry:'Banking Software',   cap:'Mid', foStock:true},
  {sym:'POLYMED.NS',    name:'Poly Medicure',          sector:'Healthcare',    industry:'Medical Devices',    cap:'Mid', foStock:false},
  {sym:'PGHH.NS',       name:'P&G Hygiene',            sector:'FMCG',          industry:'Personal Products',  cap:'Mid', foStock:false},
  {sym:'TORNTPOWER.NS', name:'Torrent Power',          sector:'Power',         industry:'Integrated Power',   cap:'Mid', foStock:true},
  {sym:'UBL.NS',        name:'United Breweries',       sector:'Consumer',      industry:'Beverages',          cap:'Mid', foStock:true},
  {sym:'VOLTAS.NS',     name:'Voltas',                 sector:'Consumer',      industry:'Air Conditioning',   cap:'Mid', foStock:true},
  {sym:'M&MFIN.NS',     name:'M&M Financial',          sector:'NBFC',          industry:'Vehicle Finance',    cap:'Mid', foStock:true},
  {sym:'SYNGENE.NS',    name:'Syngene International',  sector:'Pharma',        industry:'CRO',                cap:'Mid', foStock:false},
  {sym:'JSWENERGY.NS',  name:'JSW Energy',             sector:'Power',         industry:'Power Generation',   cap:'Mid', foStock:true},
  {sym:'ICICIGI.NS',    name:'ICICI Lombard',          sector:'Insurance',     industry:'General Insurance',  cap:'Mid', foStock:true},
  {sym:'KFINTECH.NS',   name:'KFin Technologies',      sector:'Fintech',       industry:'Financial Services', cap:'Mid', foStock:false},
  {sym:'ENDURANCE.NS',  name:'Endurance Technologies', sector:'Auto Ancillary',industry:'Auto Parts',         cap:'Mid', foStock:false},
  {sym:'ESCORTS.NS',    name:'Escorts Kubota',         sector:'Auto',          industry:'Farm Equipment',     cap:'Mid', foStock:true},
  {sym:'EXIDEIND.NS',   name:'Exide Industries',       sector:'Auto Ancillary',industry:'Batteries',          cap:'Mid', foStock:true},
  {sym:'GSPL.NS',       name:'Gujarat State Petronet', sector:'Energy',        industry:'Gas Pipelines',      cap:'Mid', foStock:true},
  {sym:'IGL.NS',        name:'Indraprastha Gas',       sector:'Energy',        industry:'Gas Distribution',   cap:'Mid', foStock:true},
  {sym:'INDUSTOWER.NS', name:'Indus Towers',           sector:'Telecom',       industry:'Telecom Infra',      cap:'Mid', foStock:true},
  {sym:'NMDC.NS',       name:'NMDC',                   sector:'Metals',        industry:'Iron Ore',           cap:'Mid', foStock:true},
  {sym:'JINDALSTEL.NS', name:'Jindal Steel',           sector:'Metals',        industry:'Steel',              cap:'Mid', foStock:true},
  {sym:'TATACHEM.NS',   name:'Tata Chemicals',         sector:'Chemicals',     industry:'Specialty Chemicals',cap:'Mid', foStock:true},
  // ── Smallcap ─────────────────────────────────────────────────────────────
  {sym:'SUZLON.NS',     name:'Suzlon Energy',          sector:'Energy',        industry:'Wind Energy',        cap:'Small', foStock:true},
  {sym:'APLAPOLLO.NS',  name:'APL Apollo Tubes',       sector:'Metals',        industry:'Steel Tubes',        cap:'Small', foStock:true},
  {sym:'CLEANSCIENCE.NS',name:'Clean Science',         sector:'Chemicals',     industry:'Specialty Chemicals',cap:'Small', foStock:false},
  {sym:'FINEORG.NS',    name:'Fine Organics',          sector:'Chemicals',     industry:'Specialty Chemicals',cap:'Small', foStock:false},
  {sym:'SOLARINDS.NS',  name:'Solar Industries',       sector:'Chemicals',     industry:'Explosives',         cap:'Small', foStock:true},
  {sym:'HEG.NS',        name:'HEG',                    sector:'Industrials',   industry:'Electrodes',         cap:'Small', foStock:true},
  {sym:'LATENTVIEW.NS', name:'Latent View Analytics',  sector:'IT',            industry:'Data Analytics',     cap:'Small', foStock:false},
  {sym:'MASTEK.NS',     name:'Mastek',                 sector:'IT',            industry:'IT Services',        cap:'Small', foStock:false},
  {sym:'CAMPUS.NS',     name:'Campus Activewear',      sector:'Consumer',      industry:'Footwear',           cap:'Small', foStock:false},
  {sym:'DELHIVERY.NS',  name:'Delhivery',              sector:'Logistics',     industry:'Courier & Delivery', cap:'Small', foStock:true},
  {sym:'ETHOSLTD.NS',   name:'Ethos',                  sector:'Consumer',      industry:'Luxury Watches',     cap:'Small', foStock:false},
  {sym:'GLAND.NS',      name:'Gland Pharma',           sector:'Pharma',        industry:'Injectables',        cap:'Small', foStock:true},
  {sym:'IOLCP.NS',      name:'IOL Chemicals',          sector:'Chemicals',     industry:'Specialty Chemicals',cap:'Small', foStock:false},
  {sym:'JKPAPER.NS',    name:'JK Paper',               sector:'Paper',         industry:'Paper Products',     cap:'Small', foStock:false},
  {sym:'KRBL.NS',       name:'KRBL',                   sector:'FMCG',          industry:'Packaged Foods',     cap:'Small', foStock:false},
  {sym:'MEDPLUS.NS',    name:'Medplus Health',         sector:'Healthcare',    industry:'Pharmacy Retail',    cap:'Small', foStock:false},
  {sym:'MOLDTKPAC.NS',  name:'Mold-Tek Packaging',     sector:'Packaging',     industry:'Packaging',          cap:'Small', foStock:false},
  {sym:'NAZARA.NS',     name:'Nazara Technologies',    sector:'Gaming',        industry:'Mobile Gaming',      cap:'Small', foStock:false},
  {sym:'RAYMOND.NS',    name:'Raymond',                sector:'Consumer',      industry:'Textiles',           cap:'Small', foStock:true},
  {sym:'REDINGTON.NS',  name:'Redington',              sector:'IT',            industry:'IT Distribution',    cap:'Small', foStock:false},
  {sym:'ROUTE.NS',      name:'Route Mobile',           sector:'IT',            industry:'Cloud Comm',         cap:'Small', foStock:false},
  {sym:'SAPPHIRE.NS',   name:'Sapphire Foods',         sector:'QSR',           industry:'Restaurants',        cap:'Small', foStock:false},
  {sym:'SHYAMMETL.NS',  name:'Shyam Metalics',         sector:'Metals',        industry:'Steel',              cap:'Small', foStock:false},
  {sym:'SPANDANA.NS',   name:'Spandana Sphoorty',      sector:'NBFC',          industry:'Microfinance',       cap:'Small', foStock:false},
  {sym:'STLTECH.NS',    name:'Sterlite Technologies',  sector:'IT',            industry:'Optical Fibre',      cap:'Small', foStock:false},
  {sym:'TEAMLEASE.NS',  name:'TeamLease Services',     sector:'HR',            industry:'Staffing',           cap:'Small', foStock:false},
  {sym:'THYROCARE.NS',  name:'Thyrocare',              sector:'Healthcare',    industry:'Diagnostics',        cap:'Small', foStock:false},
  {sym:'UJJIVANSFB.NS', name:'Ujjivan SFB',            sector:'Banking',       industry:'Small Finance Bank', cap:'Small', foStock:true},
  {sym:'UTIAMC.NS',     name:'UTI AMC',                sector:'Fintech',       industry:'Asset Management',   cap:'Small', foStock:false},
  {sym:'VAIBHAVGBL.NS', name:'Vaibhav Global',         sector:'Consumer',      industry:'Jewellery Retail',   cap:'Small', foStock:false},
  {sym:'VMART.NS',      name:'V-Mart Retail',          sector:'Retail',        industry:'Value Retail',       cap:'Small', foStock:false},
  {sym:'WELCORP.NS',    name:'Welspun Corp',           sector:'Metals',        industry:'Pipes',              cap:'Small', foStock:false},
  {sym:'ZENTEC.NS',     name:'Zen Technologies',       sector:'Defence',       industry:'Defence Training',   cap:'Small', foStock:false},
  {sym:'NLCINDIA.NS',   name:'NLC India',              sector:'Power',         industry:'Power & Lignite',    cap:'Small', foStock:false},
  {sym:'GLOBUSSPR.NS',  name:'Globus Spirits',         sector:'Consumer',      industry:'Spirits',            cap:'Small', foStock:false},
  {sym:'HEG.NS',        name:'HEG',                    sector:'Industrials',   industry:'Graphite Electrodes',cap:'Small', foStock:true},
  {sym:'MAHINDCIE.NS',  name:'Mahindra CIE Auto',      sector:'Auto Ancillary',industry:'Auto Parts',         cap:'Small', foStock:false},
  {sym:'NETWORK18.NS',  name:'Network18 Media',        sector:'Media',         industry:'Broadcasting',       cap:'Small', foStock:false},
  {sym:'VSTIND.NS',     name:'VST Industries',         sector:'FMCG',          industry:'Tobacco',            cap:'Small', foStock:false},
  {sym:'UNIPARTS.NS',   name:'Uniparts India',         sector:'Auto Ancillary',industry:'Auto Parts',         cap:'Small', foStock:false},
  // ── Additional F&O Stocks ─────────────────────────────────────────────────
  {sym:'ABFRL.NS',      name:'Aditya Birla Fashion',   sector:'Retail',        industry:'Fashion Retail',     cap:'Mid', foStock:true},
  {sym:'ACC.NS',        name:'ACC',                    sector:'Cement',        industry:'Cement',             cap:'Mid', foStock:true},
  {sym:'AMBUJACEM.NS',  name:'Ambuja Cements',         sector:'Cement',        industry:'Cement',             cap:'Large', foStock:true},
  {sym:'ATUL.NS',       name:'Atul',                   sector:'Chemicals',     industry:'Specialty Chemicals',cap:'Mid', foStock:false},
  {sym:'BANDHANBNK.NS', name:'Bandhan Bank',           sector:'Banking',       industry:'Private Bank',       cap:'Mid', foStock:true},
  {sym:'BERGEPAINT.NS', name:'Berger Paints',          sector:'Consumer',      industry:'Paints',             cap:'Mid', foStock:true},
  {sym:'BOSCHLTD.NS',   name:'Bosch',                  sector:'Auto Ancillary',industry:'Auto Parts',         cap:'Large', foStock:true},
  {sym:'COLPAL.NS',     name:'Colgate-Palmolive',      sector:'FMCG',          industry:'Personal Products',  cap:'Large', foStock:true},
  {sym:'COROMANDEL.NS', name:'Coromandel International',sector:'Agrochem',     industry:'Fertilisers',        cap:'Mid', foStock:true},
  {sym:'EICHERMOT.NS',  name:'Eicher Motors',          sector:'Auto',          industry:'2-Wheelers',         cap:'Large', foStock:true},
  {sym:'EMAMILTD.NS',   name:'Emami',                  sector:'FMCG',          industry:'Personal Products',  cap:'Mid', foStock:true},
  {sym:'GUJGASLTD.NS',  name:'Gujarat Gas',            sector:'Energy',        industry:'Gas Distribution',   cap:'Mid', foStock:true},
  {sym:'HINDPETRO.NS',  name:'HPCL',                   sector:'Energy',        industry:'Oil Refining',       cap:'Large', foStock:true},
  {sym:'HONAUT.NS',     name:'Honeywell Automation',   sector:'Capital Goods', industry:'Industrial Automation',cap:'Large',foStock:false},
  {sym:'ICICIPRULI.NS', name:'ICICI Prudential Life',  sector:'Insurance',     industry:'Life Insurance',     cap:'Large', foStock:true},
  {sym:'IPCALAB.NS',    name:'Ipca Laboratories',      sector:'Pharma',        industry:'Pharma',             cap:'Mid', foStock:true},
  {sym:'IRB.NS',        name:'IRB Infrastructure',     sector:'Infra',         industry:'Road Infra',         cap:'Mid', foStock:true},
  {sym:'JUBILANT.NS',   name:'Jubilant Ingrevia',      sector:'Chemicals',     industry:'Specialty Chemicals',cap:'Mid', foStock:false},
  {sym:'LALPATHLAB.NS', name:'Dr Lal Pathlabs',        sector:'Healthcare',    industry:'Diagnostics',        cap:'Mid', foStock:true},
  {sym:'LAURUSLABS.NS', name:'Laurus Labs',            sector:'Pharma',        industry:'API',                cap:'Mid', foStock:true},
  {sym:'MGL.NS',        name:'Mahanagar Gas',          sector:'Energy',        industry:'Gas Distribution',   cap:'Mid', foStock:true},
  {sym:'MFSL.NS',       name:'Max Financial Services', sector:'Insurance',     industry:'Life Insurance',     cap:'Mid', foStock:true},
  {sym:'NATCOPHARM.NS', name:'Natco Pharma',           sector:'Pharma',        industry:'Generics',           cap:'Mid', foStock:false},
  {sym:'NBCC.NS',       name:'NBCC India',             sector:'Infra',         industry:'Construction',       cap:'Mid', foStock:true},
  {sym:'PETRONET.NS',   name:'Petronet LNG',           sector:'Energy',        industry:'LNG',                cap:'Large', foStock:true},
  {sym:'PIDILITIND.NS', name:'Pidilite Industries',    sector:'Chemicals',     industry:'Adhesives',          cap:'Large', foStock:true},
  {sym:'PIRAMALENT.NS', name:'Piramal Enterprises',    sector:'NBFC',          industry:'Diversified Finance',cap:'Mid', foStock:true},
  {sym:'RBLBANK.NS',    name:'RBL Bank',               sector:'Banking',       industry:'Private Bank',       cap:'Mid', foStock:true},
  {sym:'RECLTD.NS',     name:'REC',                    sector:'NBFC',          industry:'Govt Finance',       cap:'Large', foStock:true},
  {sym:'SBICARD.NS',    name:'SBI Cards',              sector:'NBFC',          industry:'Credit Cards',       cap:'Large', foStock:true},
  {sym:'SBILIFE.NS',    name:'SBI Life Insurance',     sector:'Insurance',     industry:'Life Insurance',     cap:'Large', foStock:true},
  {sym:'SUNDARMFIN.NS', name:'Sundaram Finance',       sector:'NBFC',          industry:'Vehicle Finance',    cap:'Mid', foStock:false},
  {sym:'SUNDRMBFAST.NS',name:'Sundram Fasteners',      sector:'Auto Ancillary',industry:'Fasteners',          cap:'Mid', foStock:false},
  {sym:'SUNTV.NS',      name:'Sun TV Network',         sector:'Media',         industry:'Broadcasting',       cap:'Mid', foStock:true},
  {sym:'TATAINVEST.NS', name:'Tata Investment',        sector:'NBFC',          industry:'Investment Holding', cap:'Mid', foStock:false},
  {sym:'TTKPRESTIG.NS', name:'TTK Prestige',           sector:'Consumer',      industry:'Kitchenware',        cap:'Mid', foStock:false},
  {sym:'WHIRLPOOL.NS',  name:'Whirlpool India',        sector:'Consumer',      industry:'Consumer Durables',  cap:'Mid', foStock:false},
  {sym:'WIPRO.NS',      name:'Wipro',                  sector:'IT',            industry:'IT Services',        cap:'Large', foStock:true},
  {sym:'ZEEL.NS',       name:'Zee Entertainment',      sector:'Media',         industry:'Broadcasting',       cap:'Mid', foStock:true},
];

// Deduplicate by sym
const seen = new Set();
const UNIVERSE = STOCK_UNIVERSE.filter(s => {
  if (seen.has(s.sym)) return false;
  seen.add(s.sym);
  return true;
});

// Build lookup
const UNIVERSE_MAP = {};
UNIVERSE.forEach(s => { UNIVERSE_MAP[s.sym] = s; });

// Sector list (unique)
const SECTORS = [...new Set(UNIVERSE.map(s => s.sector))].sort();

// Industry list (unique)
const INDUSTRIES = [...new Set(UNIVERSE.map(s => s.industry))].sort();

module.exports = { UNIVERSE, UNIVERSE_MAP, SECTORS, INDUSTRIES };
